---
- name: GET STRUCTURED DATA BACK FROM CLI DEVICES
  hosts: all
  connection: local
  gather_facts: False
  vars:
  - results: results
  tasks:
    - file: path={{results}} state=directory
      run_once: true
    - name: TEST Nick Russo Filter
      ios_command:
        #connection: ssh
        #platform: cisco_ios_ssh
        commands: show lacp neighbor | include ^Channel|^Gi
        #host: "{{ inventory_hostname }}"
        #username: "{{ ansible_user }}"
        #password: "{{ ansible_ssh_pass }}"
      register: AXS_LACP_TEXT
    - set_fact: AXS_LACP_NEI={{ AXS_LACP_TEXT | ios_lacp_neighbor }}
    - name: "DEBUG >> Dump LACP session data"
      debug:
        msg: "{{ AXS_LACP_NEI }}"
        verbosity: 1
    #- copy: content="{{facts |to_nice_yaml(indent=4)}}" dest={{results}}/{{inventory_hostname}}.yml
    #- debug: var=facts
