---
- name: GET STRUCTURED DATA BACK FROM CLI DEVICES
  hosts: all
  connection: local
  gather_facts: False
  vars:
  - results: results
  tasks:
    - file: path={{results}} state=directory
      run_once: true
    - name: TEST NAPALM MODULE
      napalm_get_facts:
        hostname={{ansible_host|default(inventory_hostname)}}
        username={{ansible_user}}
        password={{ansible_ssh_pass}}
        dev_os={{ansible_os}}
        filter='interfaces,interfaces_ip'
      register: facts
    - copy: content="{{facts|to_nice_yaml(indent=4)}}" dest={{results}}/{{inventory_hostname}}.yml
